Set up CI with Azure Pipelines
[skip ci]

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -15,9 +15,8 @@ variables:
   containerRegistry: 'testcontainerregistrydemo.azurecr.io'
   dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
   tag: '$(Build.BuildId)'
-
-  # Agent VM image name
   vmImageName: 'ubuntu-latest'
+  clairServerUrl: 'http://172.208.88.203:6060'
 
 stages:
 - stage: Build
@@ -28,6 +27,26 @@ stages:
     pool:
       vmImage: $(vmImageName)
     steps:
+    
+    - script: |
+        wget https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64
+        mv clair-scanner_linux_amd64 clair-scanner
+        chmod +x clair-scanner
+      displayName: 'Install clair-scanner'
+
+    - script: |
+        ./clair-scanner --clair="${clairServerUrl}" --ip="YOUR_AGENT_IP" --reportAll=true --log=debug --reportPath=clair-report.json $(imageRepository).tar || true
+      displayName: 'Scan Docker image with clair-scanner'
+      env:
+        YOUR_AGENT_IP: 'Host IP where Clair can reach this scanner'
+
+    - script: |
+        if grep -q "High" clair-report.json; then
+          echo "High vulnerabilities found, failing build"
+          exit 1
+        fi
+      displayName: 'Check for vulnerabilities'
+
     - task: Docker@2
       displayName: Build and push an image to container registry
       inputs:
@@ -37,3 +56,5 @@ stages:
         containerRegistry: $(dockerRegistryServiceConnection)
         tags: |
           $(tag)
+    
+      
